# copied from https://docs.docker.com/compose/

version: "3.9"  # optional since v1.27.0
services:
  jupyter:
    build: .
    image: deargle/my-datascience-notebook
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
